### ISSUE TITLE
Rules for Selection of Praetor May Become Incorrect

### ISSUE THREAD

**Issue by deucemckenzie** [stevenvergenz/secret-caesar#11]
During the course of a 7 player game the rules for selecting Praetor did not work properly. On one turn a player was able to select the consul from the last turn as Praetor. Then in the very next round the consul was unable to select a legal target (a player who was not part of the prior round's leadership)

**Comment by stevenvergenz** [comment]
This sounds like a bug. You should only be able to do this in the 5 player version.

**Comment by deucemckenzie** [comment]
Note: We were down to 5 players since two had been executed. Perhaps this is the expected behavior. I unfortunately will not have time to check rulebook until the evening.

**Comment by stevenvergenz** [comment]
Behaves as intended.
