### ISSUE TITLE
Veto Card Passed as Though Part of Policy Deck

### ISSUE THREAD

**Issue by deucemckenzie** [stevenvergenz/secret-caesar#12]
Selection of veto card by Praetor has caused the game to crash with all cards disappearing from the table.

**Comment by deucemckenzie** [comment]
Fixed description, since I realized I didn't understand how the Veto feature was supposed to work, since I have never been involved in one before. Regardless, the game crashed upon selection of the veto card.

**Comment by stevenvergenz** [comment]
Will check logs, update tomorrow.

**Comment by deucemckenzie** [comment]
Game the issue a more appropriate name

**Comment by stevenvergenz** [comment]
Aha! All the cards use the same material, so when the veto fade effect happened it faded all the policies. Should be fixed now!
